//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace WcfService5_CurrencyConvertor.webRefConvertor {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetChannelCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChannelForChannelCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConvertGOOGOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::WcfService5_CurrencyConvertor.Properties.Settings.Default.WcfService5_CurrencyConvertor_webRefConvertor_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetChannelCategoryCompletedEventHandler GetChannelCategoryCompleted;
        
        /// <remarks/>
        public event GetChannelForChannelCategoryCompletedEventHandler GetChannelForChannelCategoryCompleted;
        
        /// <remarks/>
        public event ConvertGOOGCompletedEventHandler ConvertGOOGCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetChannelCategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CascadingDropDownNameValue[] GetChannelCategory(string knownCategoryValues, string category) {
            object[] results = this.Invoke("GetChannelCategory", new object[] {
                        knownCategoryValues,
                        category});
            return ((CascadingDropDownNameValue[])(results[0]));
        }
        
        /// <remarks/>
        public void GetChannelCategoryAsync(string knownCategoryValues, string category) {
            this.GetChannelCategoryAsync(knownCategoryValues, category, null);
        }
        
        /// <remarks/>
        public void GetChannelCategoryAsync(string knownCategoryValues, string category, object userState) {
            if ((this.GetChannelCategoryOperationCompleted == null)) {
                this.GetChannelCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChannelCategoryOperationCompleted);
            }
            this.InvokeAsync("GetChannelCategory", new object[] {
                        knownCategoryValues,
                        category}, this.GetChannelCategoryOperationCompleted, userState);
        }
        
        private void OnGetChannelCategoryOperationCompleted(object arg) {
            if ((this.GetChannelCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChannelCategoryCompleted(this, new GetChannelCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetChannelForChannelCategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CascadingDropDownNameValue[] GetChannelForChannelCategory(string knownCategoryValues, string category) {
            object[] results = this.Invoke("GetChannelForChannelCategory", new object[] {
                        knownCategoryValues,
                        category});
            return ((CascadingDropDownNameValue[])(results[0]));
        }
        
        /// <remarks/>
        public void GetChannelForChannelCategoryAsync(string knownCategoryValues, string category) {
            this.GetChannelForChannelCategoryAsync(knownCategoryValues, category, null);
        }
        
        /// <remarks/>
        public void GetChannelForChannelCategoryAsync(string knownCategoryValues, string category, object userState) {
            if ((this.GetChannelForChannelCategoryOperationCompleted == null)) {
                this.GetChannelForChannelCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChannelForChannelCategoryOperationCompleted);
            }
            this.InvokeAsync("GetChannelForChannelCategory", new object[] {
                        knownCategoryValues,
                        category}, this.GetChannelForChannelCategoryOperationCompleted, userState);
        }
        
        private void OnGetChannelForChannelCategoryOperationCompleted(object arg) {
            if ((this.GetChannelForChannelCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChannelForChannelCategoryCompleted(this, new GetChannelForChannelCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConvertGOOG", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal ConvertGOOG(decimal amount, string fromCurrency, string toCurrency) {
            object[] results = this.Invoke("ConvertGOOG", new object[] {
                        amount,
                        fromCurrency,
                        toCurrency});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void ConvertGOOGAsync(decimal amount, string fromCurrency, string toCurrency) {
            this.ConvertGOOGAsync(amount, fromCurrency, toCurrency, null);
        }
        
        /// <remarks/>
        public void ConvertGOOGAsync(decimal amount, string fromCurrency, string toCurrency, object userState) {
            if ((this.ConvertGOOGOperationCompleted == null)) {
                this.ConvertGOOGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConvertGOOGOperationCompleted);
            }
            this.InvokeAsync("ConvertGOOG", new object[] {
                        amount,
                        fromCurrency,
                        toCurrency}, this.ConvertGOOGOperationCompleted, userState);
        }
        
        private void OnConvertGOOGOperationCompleted(object arg) {
            if ((this.ConvertGOOGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConvertGOOGCompleted(this, new ConvertGOOGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CascadingDropDownNameValue {
        
        private string nameField;
        
        private string valueField;
        
        private bool isDefaultValueField;
        
        private string optionTitleField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public bool isDefaultValue {
            get {
                return this.isDefaultValueField;
            }
            set {
                this.isDefaultValueField = value;
            }
        }
        
        /// <remarks/>
        public string optionTitle {
            get {
                return this.optionTitleField;
            }
            set {
                this.optionTitleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetChannelCategoryCompletedEventHandler(object sender, GetChannelCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChannelCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChannelCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CascadingDropDownNameValue[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CascadingDropDownNameValue[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetChannelForChannelCategoryCompletedEventHandler(object sender, GetChannelForChannelCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChannelForChannelCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChannelForChannelCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CascadingDropDownNameValue[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CascadingDropDownNameValue[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ConvertGOOGCompletedEventHandler(object sender, ConvertGOOGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConvertGOOGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConvertGOOGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591